<div class="dashboard">
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <div class="box-account box-info">
        <div class="box-head">
            <h2>MY BUY TO RENT PORTFOLIO</h2>
        </div>

        <?php echo $this->getChildHtml('customer_form_register'); ?>
        <?php /*echo $this->getChildHtml('page/html_pager'); */?>

        <?php /*$collection = $this->getCollection(); */?>
        <?php $rents = $this->getCurrRents(); ?>
        <table class="account-rent-table data-table">
            <tr class="header">
                <th>ID order</th>
                <th>Product</th>
                <th>Date</th>
                <th>Total/count</th>
            </tr>
            <?php foreach ($rents as $key => $val): ?>
                <tr>
                    <td><?= $val['order_id'] ?></td>
                    <td>
                        <a href="<?= $val['product'][1] ?>"><?= $val['name'] ?></a>
                        <a href="<?= $val['product'][1] ?>"><img src="<?= $val['product'][0] ?>" alt=""></a>
                    </td>
                    <td><?= date('d/m/Y', strtotime($val['created_at'])) ?></td>
                    <td>&#163;<?= $val['base_grand_total'] ?> for <?= $val['total_item_count'] ?> items</td>
                    <?php /*
                    <td><?= $val->getIdOrder() ?></td>
                    <td><?= $val->getSku() ?></td>
                    <td><?= $val->getImg() ?></td>
                    <td><?= $val->getFdate() ?></td>
                    <td><?= $val->getTdate() ?></td>
                    */ ?>
                </tr>
            <?php endforeach; ?>
        </table>

        <?php echo $this->getPagerHtml() ?>
        <?php echo $this->getToolbarHtml() ?>
    </div>
</div>